#!/bin/bash -e
# Copyright (C) 2023 Simo Sorce <simo@redhat.com>
# SPDX-License-Identifier: Apache-2.0

source "${TESTSSRCDIR}/helpers.sh"

title PARA "Test SSL_CTX creation"
$CHECKER ./tlsctx

title PARA "Test an actual TLS connection"
rm -f "${TMPPDIR}/s_server_input"
rm -f "${TMPPDIR}/s_server_output"

PORT=23456
expect -c "spawn $CHECKER openssl s_server -accept \"${PORT}\" -naccept 1 -key \"${PRIURI}\" -cert \"${CRTURI}\";
           set timeout 60;
           expect {
              \"ACCEPT\" {};
              default {exit 1};
           }
           set child_pid [fork];
           if {\$child_pid == -1} {
               exit 1;
           } elseif {\$child_pid == 0} {
               spawn $CHECKER openssl s_client -connect \"localhost:${PORT}\" -quiet;
               expect {
                  \" TLS SUCCESSFUL \" {exit 0};
                  default {exit 1};
               }
           } else {
               expect {
                   \"END SSL SESSION PARAMETERS\" {};
                   default {exit 1};
               }
               send \" TLS SUCCESSFUL \n\"
               expect {
                   \"1 server accepts that finished\" {exit 0;};
                   default {exit 1};
               }
           }
           exit 1;"

exit 0;
